events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    upstream frontend {
        server homeos-frontend:5173; 
    }

    upstream auth_backend {
        server homeos-auth:8001;
    }

    upstream system_backend {
        server homeos-system:8002;
    }

    resolver 127.0.0.11 valid=15s;

    # Przekierowanie HTTP -> HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # Główny serwer HTTPS
    server {
        listen 443 ssl;
        server_name localhost;
        
        client_max_body_size 25M;

        # Certyfikaty SSL
        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        # Wspólne nagłówki
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 1. Mikroserwis AUTH (wszystko pod /api idzie tutaj)
        location /api {
            rewrite ^/api/?(.*) /$1 break;
            proxy_pass http://auth_backend;
        }

        # Pliki statyczne (awatary) z mikroserwisu auth
        location /static {
            proxy_pass http://auth_backend;
        }

        # 2. Mikroserwis SYSTEM (wszystko pod /system idzie tutaj)
        location /system {
            rewrite ^/system/?(.*) /$1 break;
            proxy_pass http://system_backend;
        }

        # 3. Frontend (cała reszta)
        location / {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}